import{a as $,S as b,i as f}from"./assets/vendor-Dpd1z_xS.js";/* empty css                      */(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const E="47542274-6332373665e9da78801fe67b7",v="https://pixabay.com/api/",I=15;async function B(r,t=1){const s=`${v}?key=${E}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${I}`;try{const{data:n}=await $.get(s);return n}catch(n){throw console.error("Error fetching images:",n.message),n}}function M(r,t,s){if(t.innerHTML="",r.hits.length===0){iziToast.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"});return}const n=r.hits.map(e=>`
      <div class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" />
        </a>
        <div class="image-info">
        <p><strong>Tags:</strong> ${e.tags}</p>
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </div>
    `).join("");t.insertAdjacentHTML("beforeend",n),setTimeout(()=>{s.refresh()},0)}const m=new b(".gallery a",{captionsData:"alt",captionDelay:250}),h=document.getElementById("search-form"),g=document.getElementById("gallery"),y=document.getElementById("loader"),p=document.getElementById("load-more"),u=document.getElementById("end-message");let i="",a=1,c=0;function P(){y.style.display="block"}function T(){y.style.display="none"}async function L(r,t){try{return P(),await B(r,t,15)}catch(s){throw console.error("Error fetching images:",s),s}finally{T()}}function l(r){p.style.display=r?"block":"none"}function w(){u.textContent="We're sorry, but you've reached the end of search results.",u.style.display="block"}function H(){var t;const r=((t=document.querySelector(".gallery-item"))==null?void 0:t.getBoundingClientRect().height)||0;window.scrollBy({top:r*2,behavior:"smooth"})}h.addEventListener("submit",async r=>{if(r.preventDefault(),i=h.elements.query.value.trim(),!i){f.error({title:"Error",message:"Please enter a search term."});return}g.innerHTML="",a=1,c=0,l(!1),u.style.display="none";try{const t=await L(i,a);c=t.totalHits,M(t,g,m),m.refresh(),l(t.hits.length===15),(t.hits.length<15||a*15>=c)&&(l(!1),w())}catch{f.error({title:"Error",message:"Failed to fetch images."})}});p.addEventListener("click",async()=>{a+=1;try{const r=await L(i,a);g.insertAdjacentHTML("beforeend",r.hits.map(t=>`<a href="${t.largeImageURL}" class="gallery-item"><img src="${t.webformatURL}" alt="${t.tags}"></a>`).join("")),m.refresh(),H(),(r.hits.length<15||a*15>=c)&&(l(!1),w())}catch{f.error({title:"Error",message:"Failed to fetch more images."})}});
//# sourceMappingURL=index.js.map
