import{a as $,S as b,i as m}from"./assets/vendor-Dpd1z_xS.js";/* empty css                      */(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&n(f)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const v="47542274-6332373665e9da78801fe67b7",I="https://pixabay.com/api/",P=15;async function B(r,t=1){const o=`${I}?key=${v}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${P}`;try{const{data:n}=await $.get(o);return n}catch(n){throw console.error("Error fetching images:",n.message),n}}function h(r,t,o){if(t.innerHTML="",r.hits.length===0){iziToast.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"});return}const n=r.hits.map(e=>`
      <div class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" />
        </a>
        <div class="image-info">
        <p><strong>Tags:</strong> ${e.tags}</p>
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </div>
    `).join("");t.insertAdjacentHTML("beforeend",n),setTimeout(()=>{o.refresh()},0)}const d=new b(".gallery a",{captionsData:"alt",captionDelay:250}),p=document.getElementById("search-form"),u=document.getElementById("gallery"),L=document.getElementById("loader"),g=document.getElementById("load-more"),y=document.getElementById("end-message");let i="",a=1,l=0;function M(){L.style.display="block"}function T(){L.style.display="none"}async function E(r,t){try{return M(),await B(r,t,15)}catch(o){throw console.error("Error fetching images:",o),o}finally{T()}}function c(r){r?g.style.display="block":g.style.display="none"}function w(){y.textContent="We're sorry, but you've reached the end of search results.",y.style.display="block"}p.addEventListener("submit",async r=>{if(r.preventDefault(),i=p.elements.query.value.trim(),!i){m.error({title:"Error",message:"Please enter a search term."});return}u.innerHTML="",a=1,l=0,c(!1),y.style.display="none";try{const t=await E(i,a);l=t.totalHits,h(t,u,d),d.refresh(),c(t.hits.length===15),(t.hits.length<15||a*15>=l)&&(c(!1),w())}catch{m.error({title:"Error",message:"Failed to fetch images."})}});g.addEventListener("click",async()=>{a+=1;try{const r=await E(i,a);h(r,u,d),d.refresh(),(r.hits.length<15||a*15>=l)&&(c(!1),w())}catch{m.error({title:"Error",message:"Failed to fetch more images."})}});
//# sourceMappingURL=index.js.map
